
      
# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
#hello
#
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Copy artifact to staging directory
      run: mkdir staging && cp target/*.jar staging

    - name: Build and analyze
      env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=java-app -Dsonar.projectName='java app'

    - name: Publish Artifacts    
      uses: actions/upload-artifact@v4
      with:
        name: Package
        path: staging

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
deploy:
    runs-on: self-hosted  # Run on your self-hosted runner
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Download Artifact
      uses: actions/download-artifact@v3
      with:
        name: python-code-artifact
    - name: Verify Downloaded Artifact
      run: |
        # List the contents of the current directory to verify the artifact is downloaded
        echo "Listing files after artifact download"
        ls -al
        echo "Listing contents of the downloaded artifact"
        ls -al  # This will show the contents of the artifact files
    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: 'ap-northeast-1'
    - name: Set up SSH private key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/my-key.pem
        chmod 600 ~/.ssh/my-key.pem  # Set appropriate permissions for the private key
    - name: Ensure target directory exists on EC2
      run: |
        ssh -i ~/.ssh/my-key.pem ubuntu@13.233.97.90 << 'EOF'
          # Ensure /home/ubuntu/app directory exists
          sudo mkdir -p /home/ubuntu/app
          sudo chown ubuntu:ubuntu /home/ubuntu/app  # Give ownership to the ubuntu user
          # Ensure it has the correct permissions
          sudo chmod 755 /home/ubuntu/app
        EOF
    - name: Deploy code to EC2
      run: |
        # Verify that the artifact directory exists and list its contents
        #echo "Checking if the artifact directory exists:"
        #ls -al artifact/
        # Copy the artifact to EC2 instance using scp with the private key
        #scp -i ~/.ssh/my-key.pem -r artifact/* ubuntu@10.0.1.207:/home/ubuntu/app
        #scp -i ~/.ssh/my-key.pem -r artifact/* ubuntu@10.0.1.207:/home/ubuntu/app
        scp -i ~/.ssh/my-key.pem -r * ubuntu@13.233.97.90:/home/ubuntu/app
        # SSH into the EC2 instance to install dependencies and start the app
        ssh -i ~/.ssh/tok.pem # This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
#hello
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Copy artifact to staging directory
      run: mkdir staging && cp target/*.jar staging

    - name: Build and analyze
      env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=java-app -Dsonar.projectName='java app'

    - name: Publish Artifacts    
      uses: actions/upload-artifact@v4
      with:
        name: Package
        path: staging

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
deploy:
    runs-on: self-hosted  # Run on your self-hosted runner
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Download Artifact
      uses: actions/download-artifact@v3
      with:
        name: python-code-artifact
    - name: Verify Downloaded Artifact
      run: |
        # List the contents of the current directory to verify the artifact is downloaded
        echo "Listing files after artifact download"
        ls -al
        echo "Listing contents of the downloaded artifact"
        ls -al  # This will show the contents of the artifact files
        
 
   - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: 'ap-south-1'
        
  - name: Set up SSH private key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/my-key.pem
        chmod 600 ~/.ssh/my-key.pem  # Set appropriate permissions for the private key


- name: Ensure target directory exists on EC2
      run: |
        ssh -i ~/.ssh/tok.pem ubuntu@ip-172-31-6-43 << 'EOF'
          # Ensure /home/ubuntu/app directory exists
          sudo mkdir -p /home/ubuntu/app
          sudo chown ubuntu:ubuntu /home/ubuntu/app  # Give ownership to the ubuntu user
          # Ensure it has the correct permissions
          sudo chmod 755 /home/ubuntu/app
        EOF
- name: Deploy code to EC2
      run: |
        # Verify that the artifact directory exists and list its contents
        #echo "Checking if the artifact directory exists:"
        #ls -al artifact/
        # Copy the artifact to EC2 instance using scp with the private key
        #scp -i ~/.ssh/tok.pem -r artifact/* ubuntu@ip-172-31-6-43:/home/ubuntu/app
        #scp -i ~/.ssh/tok.pem -r artifact/* ubuntu@ip-172-31-6-43:/home/ubuntu/app
        scp -i ~/.ssh/tok.pem -r * ubuntu@ip-172-31-6-43:/home/ubuntu/app
        # SSH into the EC2 instance to install dependencies and start the app
        ssh -i ~/.ssh/tok.pem ubuntu@ip-172-31-6-43 << 'EOF'
          cd /home/ubuntu/app
          # Install dependencies if not already installed
          python -m pip install --upgrade pip
          pip install pytest
          # Start the Python app (adjust the command as needed)
          nohup python code/addition.py &
          echo "Application started."
        EOF

      
 << 'EOF'
          cd /home/ubuntu/app
          # Install dependencies if not already installed
          python -m pip install --upgrade pip
          pip install pytest
          # Start the Python app (adjust the command as needed)
          nohup python code/addition.py &
          echo "Application started."
        EOF

      
